apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalogue-db
  name: catalogue-db
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 3306
  selector:
    app: catalogue-db
status:
  loadBalancer: {}
