apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: catalogue
  name: catalogue
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: catalogue
status:
  loadBalancer: {}
