apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: catalogue-db
    version: v1
  name: catalogue-db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: catalogue-db
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          value: socksdb
        - name: MYSQL_ROOT_PASSWORD
        image: weaveworksdemos/catalogue-db:0.3.0
        name: catalogue-db
        ports:
        - containerPort: 3306
        resources: {}
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
      hostname: catalogue-db
      restartPolicy: Always
status: {}
