apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: front-end
  name: front-end
spec:
  ports:
  - name: "http"
    port: 8079
    targetPort: 8079
    protocol: TCP
  selector:
    app: front-end
status:
  loadBalancer: {}
